### ISSUE TITLE
Export XML Configuration document not working

### ISSUE THREAD

**Issue by SoroTrestal** [jumpinjackie/fdotoolbox#70]
Hi Jackie, thanks for the new version of fdotoolbox!

I encoutered an error following an old thread of you: [https://themapguyde.blogspot.com/2010/09/using-fdo-schema-overrides-redux.html](url)

If I try to export the schema to xml with the export function in 1.5 I receive the following error:

**The given key is not present in the dictionary.**

![image](https://user-images.githubusercontent.com/22880426/89547868-9508b280-d806-11ea-9500-b4289213f6b2.png)

**Comment by jumpinjackie** [comment]
Assuming you're using SQL Server would it be possible to get a the DDL export (a .sql file containing all the CREATE SCHEMA/TABLE/VIEW/INDEX/CONSTRAINT statements) of this database so I can try to reproduce the problem? If this database structure is sensitive information, you can email the DDL export directly to me instead of attaching the files to this issue.

**Comment by SoroTrestal** [comment]
Hi Jackie, actually I'm using PostgreSQL version 9.6.

I'll send you the SQL through mail, thanks in advance.
